# Generated by Django 4.2.9 on 2024-03-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='name_version',
            new_name='name',
        ),
    ]
